/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Amrina
 */
public class POSTTEST3 extends javax.swing.JFrame {

    /**
     * Creates new form POSTTEST3
     */
    public POSTTEST3() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrame1 = new javax.swing.JFrame();
        panelBtnMenu = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        panelKonten = new javax.swing.JPanel();
        panelProfile = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        panelHome = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        panelBtnMenu1 = new javax.swing.JPanel();
        BHome = new javax.swing.JButton();
        BProfil = new javax.swing.JButton();
        BGaleri = new javax.swing.JButton();
        BInformasi = new javax.swing.JButton();
        BAbout = new javax.swing.JButton();
        BExit = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        panelKonten1 = new javax.swing.JPanel();
        Pprofil = new javax.swing.JPanel();
        jLabelProfil = new javax.swing.JLabel();
        Pgaleri = new javax.swing.JPanel();
        jLabelGaleri = new javax.swing.JLabel();
        Phome = new javax.swing.JPanel();
        jLabelHome = new javax.swing.JLabel();
        PInformasi = new javax.swing.JPanel();
        jLabelInformasi = new javax.swing.JLabel();
        PKontak = new javax.swing.JPanel();
        jLabelKontak = new javax.swing.JLabel();

        jFrame1.setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelBtnMenu.setBackground(new java.awt.Color(0, 153, 255));
        panelBtnMenu.setLayout(new java.awt.GridLayout(1, 0, 30, 0));

        jButton1.setText("Home");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        panelBtnMenu.add(jButton1);

        jButton2.setText("Profile");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        panelBtnMenu.add(jButton2);

        jButton3.setText("Exit");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        panelBtnMenu.add(jButton3);

        panelKonten.setBackground(new java.awt.Color(0, 153, 255));
        panelKonten.setLayout(new java.awt.CardLayout());

        panelProfile.setBackground(new java.awt.Color(255, 255, 51));

        jLabel2.setText("My Profile");

        javax.swing.GroupLayout panelProfileLayout = new javax.swing.GroupLayout(panelProfile);
        panelProfile.setLayout(panelProfileLayout);
        panelProfileLayout.setHorizontalGroup(
            panelProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelProfileLayout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(jLabel2)
                .addContainerGap(434, Short.MAX_VALUE))
        );
        panelProfileLayout.setVerticalGroup(
            panelProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelProfileLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addContainerGap(258, Short.MAX_VALUE))
        );

        panelKonten.add(panelProfile, "card3");

        panelHome.setBackground(new java.awt.Color(255, 102, 255));

        jLabel1.setText("Welcome to My Apps");

        javax.swing.GroupLayout panelHomeLayout = new javax.swing.GroupLayout(panelHome);
        panelHome.setLayout(panelHomeLayout);
        panelHomeLayout.setHorizontalGroup(
            panelHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelHomeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(400, Short.MAX_VALUE))
        );
        panelHomeLayout.setVerticalGroup(
            panelHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelHomeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelKonten.add(panelHome, "card2");

        jLabel3.setFont(new java.awt.Font("Lucida Handwriting", 1, 24)); // NOI18N
        jLabel3.setText("APLIKASI DESKTOP");

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jFrame1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(panelKonten, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelBtnMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(jFrame1Layout.createSequentialGroup()
                .addGap(161, 161, 161)
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jFrame1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addGap(34, 34, 34)
                .addComponent(panelBtnMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(panelKonten, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelBtnMenu1.setBackground(new java.awt.Color(0, 153, 255));
        panelBtnMenu1.setLayout(new java.awt.GridLayout());

        BHome.setText("Home");
        BHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BHomeActionPerformed(evt);
            }
        });
        panelBtnMenu1.add(BHome);

        BProfil.setText("Profile");
        BProfil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BProfilActionPerformed(evt);
            }
        });
        panelBtnMenu1.add(BProfil);

        BGaleri.setText("Galeri");
        BGaleri.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BGaleriActionPerformed(evt);
            }
        });
        panelBtnMenu1.add(BGaleri);

        BInformasi.setText("Informasi");
        BInformasi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BInformasiActionPerformed(evt);
            }
        });
        panelBtnMenu1.add(BInformasi);

        BAbout.setText("About");
        BAbout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BAboutActionPerformed(evt);
            }
        });
        panelBtnMenu1.add(BAbout);

        BExit.setText("Exit");
        BExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BExitActionPerformed(evt);
            }
        });
        panelBtnMenu1.add(BExit);

        jLabel4.setFont(new java.awt.Font("Lucida Handwriting", 1, 24)); // NOI18N
        jLabel4.setIcon(new javax.swing.ImageIcon("D:\\FKTI\\S4\\Praktikum Visual\\1.JPG")); // NOI18N

        panelKonten1.setBackground(new java.awt.Color(0, 153, 255));
        panelKonten1.setLayout(new java.awt.CardLayout());

        jLabelProfil.setIcon(new javax.swing.ImageIcon("D:\\FKTI\\S4\\Praktikum Visual\\3.JPG")); // NOI18N

        javax.swing.GroupLayout PprofilLayout = new javax.swing.GroupLayout(Pprofil);
        Pprofil.setLayout(PprofilLayout);
        PprofilLayout.setHorizontalGroup(
            PprofilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PprofilLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabelProfil)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PprofilLayout.setVerticalGroup(
            PprofilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PprofilLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jLabelProfil)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelKonten1.add(Pprofil, "card3");

        jLabelGaleri.setIcon(new javax.swing.ImageIcon("D:\\FKTI\\S4\\Praktikum Visual\\4.JPG")); // NOI18N

        javax.swing.GroupLayout PgaleriLayout = new javax.swing.GroupLayout(Pgaleri);
        Pgaleri.setLayout(PgaleriLayout);
        PgaleriLayout.setHorizontalGroup(
            PgaleriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PgaleriLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabelGaleri)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PgaleriLayout.setVerticalGroup(
            PgaleriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PgaleriLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jLabelGaleri)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelKonten1.add(Pgaleri, "card4");

        jLabelHome.setIcon(new javax.swing.ImageIcon("D:\\FKTI\\S4\\Praktikum Visual\\2.JPG")); // NOI18N

        javax.swing.GroupLayout PhomeLayout = new javax.swing.GroupLayout(Phome);
        Phome.setLayout(PhomeLayout);
        PhomeLayout.setHorizontalGroup(
            PhomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PhomeLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabelHome)
                .addContainerGap(432, Short.MAX_VALUE))
        );
        PhomeLayout.setVerticalGroup(
            PhomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PhomeLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jLabelHome, javax.swing.GroupLayout.PREFERRED_SIZE, 862, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(38, Short.MAX_VALUE))
        );

        panelKonten1.add(Phome, "card2");

        jLabelInformasi.setIcon(new javax.swing.ImageIcon("D:\\FKTI\\S4\\Praktikum Visual\\5.JPG")); // NOI18N

        javax.swing.GroupLayout PInformasiLayout = new javax.swing.GroupLayout(PInformasi);
        PInformasi.setLayout(PInformasiLayout);
        PInformasiLayout.setHorizontalGroup(
            PInformasiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PInformasiLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabelInformasi)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PInformasiLayout.setVerticalGroup(
            PInformasiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PInformasiLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jLabelInformasi)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelKonten1.add(PInformasi, "card4");

        jLabelKontak.setIcon(new javax.swing.ImageIcon("D:\\FKTI\\S4\\Praktikum Visual\\6.JPG")); // NOI18N

        javax.swing.GroupLayout PKontakLayout = new javax.swing.GroupLayout(PKontak);
        PKontak.setLayout(PKontakLayout);
        PKontakLayout.setHorizontalGroup(
            PKontakLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PKontakLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabelKontak)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PKontakLayout.setVerticalGroup(
            PKontakLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PKontakLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jLabelKontak)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelKonten1.add(PKontak, "card4");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(panelKonten1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(panelBtnMenu1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelBtnMenu1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelKonten1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        panelHome.setVisible(true);
        panelProfile.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        panelProfile.setVisible(true);
        panelHome.setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void BGaleriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BGaleriActionPerformed
        // TODO add your handling code here:
        Pgaleri.setVisible(true);
        Phome.setVisible(false);
        PInformasi.setVisible(false);
        PKontak.setVisible(false);
        Pprofil.setVisible(false);
    }//GEN-LAST:event_BGaleriActionPerformed

    private void BProfilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BProfilActionPerformed
        // TODO add your handling code here:
        Pprofil.setVisible(true);
        Pgaleri.setVisible(false);
        PInformasi.setVisible(false);
        PKontak.setVisible(false);
        Phome.setVisible(false);
    }//GEN-LAST:event_BProfilActionPerformed

    private void BHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BHomeActionPerformed
        // TODO add your handling code here:
        Phome.setVisible(true);
        Pgaleri.setVisible(false);
        PInformasi.setVisible(false);
        PKontak.setVisible(false);
        Pprofil.setVisible(false);
    }//GEN-LAST:event_BHomeActionPerformed

    private void BInformasiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BInformasiActionPerformed
        // TODO add your handling code here:
        PInformasi.setVisible(true);
        Pgaleri.setVisible(false);
        Phome.setVisible(false);
        PKontak.setVisible(false);
        Pprofil.setVisible(false);
        
    }//GEN-LAST:event_BInformasiActionPerformed

    private void BAboutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BAboutActionPerformed
        // TODO add your handling code here:
        PKontak.setVisible(true);
        Pgaleri.setVisible(false);
        PInformasi.setVisible(false);
        Phome.setVisible(false);
        Pprofil.setVisible(false);
    }//GEN-LAST:event_BAboutActionPerformed

    private void BExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BExitActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_BExitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(POSTTEST3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(POSTTEST3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(POSTTEST3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(POSTTEST3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new POSTTEST3().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BAbout;
    private javax.swing.JButton BExit;
    private javax.swing.JButton BGaleri;
    private javax.swing.JButton BHome;
    private javax.swing.JButton BInformasi;
    private javax.swing.JButton BProfil;
    private javax.swing.JPanel PInformasi;
    private javax.swing.JPanel PKontak;
    private javax.swing.JPanel Pgaleri;
    private javax.swing.JPanel Phome;
    private javax.swing.JPanel Pprofil;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabelGaleri;
    private javax.swing.JLabel jLabelHome;
    private javax.swing.JLabel jLabelInformasi;
    private javax.swing.JLabel jLabelKontak;
    private javax.swing.JLabel jLabelProfil;
    private javax.swing.JPanel panelBtnMenu;
    private javax.swing.JPanel panelBtnMenu1;
    private javax.swing.JPanel panelHome;
    private javax.swing.JPanel panelKonten;
    private javax.swing.JPanel panelKonten1;
    private javax.swing.JPanel panelProfile;
    // End of variables declaration//GEN-END:variables
}
